/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p3.vistas;

import java.util.logging.Level;
import java.util.logging.Logger;
import p3.Simulacion;
import p3.gestionarDatos;

/**
 *
 * @author moren
 */
public class Simulador extends javax.swing.JFrame 
{
    gestionarDatos gd;
    Simulacion s;
    /**
     * Creates new form NewJFrame
     */
    public Simulador() 
    {
        super("Simulador Ecosistema Polo Sur");
        initComponents();
        gd = new gestionarDatos();
        //s = gd.cargarDatos();
        s = new Simulacion();
        s.crearEntorno();
        labelDia.setText("" + s.getDia());
        labelEsquimal.setText("" + s.getNumEsquimales());
        labelOso.setText("" + s.getNumOsos());
        labelMorsa.setText("" + s.getNumMorsas());
        labelFoca.setText("" + s.getNumFocas());
        labelPez.setText("" + s.getNumPeces());
        labelKrill.setText("" + s.getNumKrill());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPez = new javax.swing.JLabel();
        labelFoca = new javax.swing.JLabel();
        labelMorsa = new javax.swing.JLabel();
        labelOso = new javax.swing.JLabel();
        labelEsquimal = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        labelKrill = new javax.swing.JLabel();
        buttonSalir = new javax.swing.JButton();
        buttonAvanzar10 = new javax.swing.JButton();
        buttonMostrar = new javax.swing.JButton();
        buttonDia = new javax.swing.JButton();
        buttonNuevoPolo = new javax.swing.JButton();
        buttonBuque = new javax.swing.JButton();
        buttonCalentamiento = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPez.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelPez.setText("0");
        getContentPane().add(labelPez, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 130, 30));

        labelFoca.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelFoca.setText("0");
        getContentPane().add(labelFoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 130, 30));

        labelMorsa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMorsa.setText("0");
        getContentPane().add(labelMorsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 130, 30));

        labelOso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelOso.setText("0");
        getContentPane().add(labelOso, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 130, 30));

        labelEsquimal.setBackground(new java.awt.Color(255, 255, 255));
        labelEsquimal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelEsquimal.setText("0");
        getContentPane().add(labelEsquimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 130, 30));

        labelDia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelDia.setText("Día 0");
        getContentPane().add(labelDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 30));

        labelKrill.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelKrill.setText("0");
        getContentPane().add(labelKrill, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 140, 30));

        buttonSalir.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        buttonSalir.setText("SALIR");
        buttonSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 220, 40));

        buttonAvanzar10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        buttonAvanzar10.setText("AVANZAR 10 DÍAS");
        buttonAvanzar10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buttonAvanzar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAvanzar10ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAvanzar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 220, 40));

        buttonMostrar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        buttonMostrar.setText("MOSTRAR DETALLES");
        buttonMostrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buttonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 40));

        buttonDia.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        buttonDia.setText("TRANSCURRIR UN DÍA");
        buttonDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buttonDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, 40));

        buttonNuevoPolo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        buttonNuevoPolo.setText("CREAR UN NUEVO POLO");
        buttonNuevoPolo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buttonNuevoPolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoPoloActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNuevoPolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, 40));

        buttonBuque.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        buttonBuque.setText("BUQUES DE PESCA");
        buttonBuque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buttonBuque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuqueActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBuque, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 220, 40));

        buttonCalentamiento.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        buttonCalentamiento.setText("CALENTAMIENTO GLOBAL");
        buttonCalentamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buttonCalentamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalentamientoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCalentamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 220, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 150, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 160, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 150, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 150, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 150, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/copia3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNuevoPoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoPoloActionPerformed
        s = new Simulacion();
        s.crearEntorno();
        labelDia.setText("" + s.getDia());
        labelEsquimal.setText("" + s.getNumEsquimales());
        labelOso.setText("" + s.getNumOsos());
        labelMorsa.setText("" + s.getNumMorsas());
        labelFoca.setText("" + s.getNumFocas());
        labelPez.setText("" + s.getNumPeces());
        labelKrill.setText("" + s.getNumKrill());
    }//GEN-LAST:event_buttonNuevoPoloActionPerformed

    private void buttonCalentamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalentamientoActionPerformed
        s.calentamientoGlobal();
        labelDia.setText("" + s.getDia());
        labelEsquimal.setText("" + s.getNumEsquimales());
        labelOso.setText("" + s.getNumOsos());
        labelMorsa.setText("" + s.getNumMorsas());
        labelFoca.setText("" + s.getNumFocas());
        labelPez.setText("" + s.getNumPeces());
        labelKrill.setText("" + s.getNumKrill());
    }//GEN-LAST:event_buttonCalentamientoActionPerformed

    private void buttonDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiaActionPerformed
        s.transcurrirDia(1);
        labelDia.setText("" + s.getDia());
        labelEsquimal.setText("" + s.getNumEsquimales());
        labelOso.setText("" + s.getNumOsos());
        labelMorsa.setText("" + s.getNumMorsas());
        labelFoca.setText("" + s.getNumFocas());
        labelPez.setText("" + s.getNumPeces());
        labelKrill.setText("" + s.getNumKrill());
    }//GEN-LAST:event_buttonDiaActionPerformed

    private void buttonAvanzar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAvanzar10ActionPerformed
        s.transcurrirDia(1);
        labelDia.setText("" + s.getDia());
        labelEsquimal.setText("" + s.getNumEsquimales());
        labelOso.setText("" + s.getNumOsos());
        labelMorsa.setText("" + s.getNumMorsas());
        labelFoca.setText("" + s.getNumFocas());
        labelPez.setText("" + s.getNumPeces());
        labelKrill.setText("" + s.getNumKrill());
        
        if(s.getNumEsquimales() == 0 && s.getNumFocas() == 0 && s.getNumKrill() == 0 && s.getNumMorsas() == 0 && s.getNumOsos() == 0 && s.getNumPeces() == 0)
        {
            gd.guardarDatos(s);
            System.exit(0);
        }
    }//GEN-LAST:event_buttonAvanzar10ActionPerformed

    private void buttonBuqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuqueActionPerformed
        s.buquesPescaMayor();
        labelDia.setText("" + s.getDia());
        labelEsquimal.setText("" + s.getNumEsquimales());
        labelOso.setText("" + s.getNumOsos());
        labelMorsa.setText("" + s.getNumMorsas());
        labelFoca.setText("" + s.getNumFocas());
        labelPez.setText("" + s.getNumPeces());
        labelKrill.setText("" + s.getNumKrill());
    }//GEN-LAST:event_buttonBuqueActionPerformed

    private void buttonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarActionPerformed
        MostrarDetalles md = new MostrarDetalles(s.mostrarDetalles());
        md.setVisible(true);
    }//GEN-LAST:event_buttonMostrarActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        gd.guardarDatos(s);
        System.exit(0);
    }//GEN-LAST:event_buttonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAvanzar10;
    private javax.swing.JButton buttonBuque;
    private javax.swing.JButton buttonCalentamiento;
    private javax.swing.JButton buttonDia;
    private javax.swing.JButton buttonMostrar;
    private javax.swing.JButton buttonNuevoPolo;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelEsquimal;
    private javax.swing.JLabel labelFoca;
    private javax.swing.JLabel labelKrill;
    private javax.swing.JLabel labelMorsa;
    private javax.swing.JLabel labelOso;
    private javax.swing.JLabel labelPez;
    // End of variables declaration//GEN-END:variables
}
